name: engzly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  motion_tab_bar_v2: ^0.4.0
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9  
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  get_it: ^8.2.0
  pinput: ^5.0.1
  pin_code_fields: ^8.0.1
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  google_maps_flutter: ^2.13.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0



  http_parser: any
  path: any
dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.4
  json_serializable: ^6.8.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/house_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/house_icon.png"

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/


  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
