name: engzly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
